### PR TITLE
re-added setMaxFileSize(String)

### PR DESCRIPTION
**Pull request by a-l-f-r-e-d**
since removing setMaxFileSize(String) causes Incompatibility to i.e. Spring boot, 
And this was a minor version release i re added this method.

### CODE REVIEW

**Comment by huxi** [comment]
This is a quite serious regression. Formerly valid Logback configurations fail with `java.lang.NoSuchMethodError` exception after upgrading to 1.1.8.

I'd suggest to merge this and release 1.1.9 as soon as possible.

**Comment by ceki** [comment]
This is supposed to be transparent. Existing logback configuration files should work without change. May I see a stack trace please?

**Comment by huxi** [comment]
spring-boot is configuring Logback programmatically.

The code in question is located in [DefaultLogbackConfiguration](https://github.com/spring-projects/spring-boot/blob/d8b7d6dfdc35d64942baf415305c4f2ba5a64171/spring-boot/src/main/java/org/springframework/boot/logging/logback/DefaultLogbackConfiguration.java#L140).

This is the default Logback configuration used by every spring-boot applications.

```
java.lang.NoSuchMethodError: ch.qos.logback.core.rolling.SizeBasedTriggeringPolicy.setMaxFileSize(Ljava/lang/String;)V
	at org.springframework.boot.logging.logback.DefaultLogbackConfiguration.fileAppender(DefaultLogbackConfiguration.java:145)
	at org.springframework.boot.logging.logback.DefaultLogbackConfiguration.apply(DefaultLogbackConfiguration.java:80)
	at org.springframework.boot.logging.logback.LogbackLoggingSystem.loadDefaults(LogbackLoggingSystem.java:133)
	at org.springframework.boot.logging.AbstractLoggingSystem.initializeWithConventions(AbstractLoggingSystem.java:75)
	at org.springframework.boot.logging.AbstractLoggingSystem.initialize(AbstractLoggingSystem.java:50)
	at org.springframework.boot.logging.logback.LogbackLoggingSystem.initialize(LogbackLoggingSystem.java:114)
	at org.springframework.boot.logging.LoggingApplicationListener.initializeSystem(LoggingApplicationListener.java:299)
	at org.springframework.boot.logging.LoggingApplicationListener.initialize(LoggingApplicationListener.java:272)
	at org.springframework.boot.logging.LoggingApplicationListener.onApplicationEnvironmentPreparedEvent(LoggingApplicationListener.java:235)
	at org.springframework.boot.logging.LoggingApplicationListener.onApplicationEvent(LoggingApplicationListener.java:208)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:166)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:138)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:121)
	at org.springframework.boot.context.event.EventPublishingRunListener.environmentPrepared(EventPublishingRunListener.java:68)
	at org.springframework.boot.SpringApplicationRunListeners.environmentPrepared(SpringApplicationRunListeners.java:54)
	at org.springframework.boot.SpringApplication.prepareEnvironment(SpringApplication.java:337)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:308)
```

**Comment by ceki** [comment]
Jörn, thank you for the details. The compiler should catch this. It's very strange that it doesn't.

**Comment by huxi** [comment]
The code causing the `java.lang.NoSuchMethodError` isn't compiled by the end-user.

It is contained in `org.springframework.boot:spring-boot:1.4.2.RELEASE` and the failure happens at runtime during automagic spring-boot configuration of Logback if Logback 1.1.8 is added to the classpath instead of Logback 1.1.7 which still worked.

I don't know how to fix that problem exactly but this incompatibility should be addressed in some backwards-compatible way.

**Comment by huxi** [comment]
Just took a quick glance at the previous code.

If you reinstate it then you should switch it around like
```java
    public void setMaxFileSize(String maxFileSize) {
        this.maxFileSize = FileSize.valueOf(maxFileSize);
        this.maxFileSizeAsString = maxFileSize;
    }
```
so `maxFileSizeAsString` is only changed if `FileSize.valueOf` didn't throw an exception.

**Comment by ceki** [comment]
The problem should be apparent at compile time when spring-boot upgrades to logback v 1.1.8. 

As mentioned earlier, Joran does not support **multiple** setters with different types for the **same** property.

**Comment by ceki** [comment]
Closing this PR as it cannot be merged.  Joran does not support multiple setters with different types for the same property.

**Comment by huxi** [comment]
Spring-Boot 1.4.3 fixes the incompatibility with Logback 1.1.8.

**Comment by mattnelson** [comment]
FYI, this is also breaking dropwizard[1]. Users will be forced to stay on logback-1.1.7 until the fix is released. This is a major regression for a patch release.

[1] https://github.com/dropwizard/dropwizard/pull/1865

```
Exception in thread "main" java.lang.NoSuchMethodError: ch.qos.logback.core.rolling.SizeBasedTriggeringPolicy.setMaxFileSize(Ljava/lang/String;)V
	at io.dropwizard.logging.FileAppenderFactory.buildAppender(FileAppenderFactory.java:231)
	at io.dropwizard.logging.FileAppenderFactory.build(FileAppenderFactory.java:198)
	at io.dropwizard.logging.DefaultLoggingFactory.configure(DefaultLoggingFactory.java:134)
	at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:81)
	at io.dropwizard.cli.Cli.run(Cli.java:75)
```
