### ISSUE TITLE
Exception when Upgraded to  1.4.13

### ISSUE THREAD

**Issue by hantsy** [qos-ch/logback#744]
https://github.com/hantsy/spring6-sandbox/pull/501

In My Spring 6 example, when upgrading to 1.4.13, it failed the tests run on Github actions.

```bash
0.040 s <<< ERROR!
java.lang.NoSuchMethodError: 'java.lang.ClassLoader ch.qos.logback.core.util.Loader.systemClassloaderIfNull(java.lang.ClassLoader)'
	at ch.qos.logback.classic.util.ContextInitializer.autoConfig(ContextInitializer.java:73)
	at ch.qos.logback.classic.util.ContextInitializer.autoConfig(ContextInitializer.java:66)
	at ch.qos.logback.classic.spi.LogbackServiceProvider.initializeLoggerContext(LogbackServiceProvider.java:52)
	at ch.qos.logback.classic.spi.LogbackServiceProvider.initialize(LogbackServiceProvider.java:41)
```

**Comment by LeadingMoominExpert** [comment]
I'm seeing the same kind of exceptions when upgrading from `1.4.11` to `1.4.12`

**Comment by beytularedzheb** [comment]
I had the same issue after the upgrade from 1.4.11 to 1.4.12 / 1.4.13. The way I fixed it was by explicitly adding logback-core dependency with the same version as logback-classic.

>
        <dependency>
            <groupId>ch.qos.logback</groupId>
            <artifactId>logback-classic</artifactId>
            <version>1.4.13</version>
        </dependency>
        <dependency>
            <groupId>ch.qos.logback</groupId>
            <artifactId>logback-core</artifactId>
            <version>1.4.13</version>
        </dependency>

**Comment by dc-oe** [comment]
We have also experienced this exception moving to 1.4.14 from 1.4.11. We have matched versions of the jars, so the workaround mentioned is not applicable to us.

**Comment by ceki** [comment]
The Loader.systemClassloaderIfNull method was added in commit bf59a63059841e14dff part of logback version 1.4.12 released on 2023-11-27. The exception is thrown only if logback-core artifact is older than 1.4.12.

@dc-oe  Please to check that the logback-core artifact is indeed version 1.4.12 or later. I rather certain that the logback-core and logback-classic versions in your project do not match.

**Comment by dc-oe** [comment]
You would be correct. We are running under Tomcat and had 2 copies under different classsloaders. Neglected to update the one in Tomcat's classloader. All is good.

**Comment by sivagnanavelu** [comment]
> I had the same issue after the upgrade from 1.4.11 to 1.4.12 / 1.4.13. The way I fixed it was by explicitly adding logback-core dependency with the same version as logback-classic.
> 
> > 
> 
> ```
>     <dependency>
>         <groupId>ch.qos.logback</groupId>
>         <artifactId>logback-classic</artifactId>
>         <version>1.4.13</version>
>     </dependency>
>     <dependency>
>         <groupId>ch.qos.logback</groupId>
>         <artifactId>logback-core</artifactId>
>         <version>1.4.13</version>
>     </dependency>
> ```

This is worked for me also. Thanks
