### ISSUE TITLE
Exception in thread "main" java.lang.NoSuchMethodError:

### ISSUE THREAD

**Issue by malikmuso** [qos-ch/logback#820]
Hello! I get this when bumping logback-classic from 1.4.14 to latest

Exception in thread "main" java.lang.NoSuchMethodError: 'void ch.qos.logback.core.model.processor.ModelInterpretationContext.setConfiguratorSupplier(java.util.function.Supplier)'
	at ch.qos.logback.classic.joran.JoranConfigurator.buildModelInterpretationContext(JoranConfigurator.java:96)
	at ch.qos.logback.core.joran.GenericXMLConfigurator.processModel(GenericXMLConfigurator.java:200)
	at ch.qos.logback.core.joran.GenericXMLConfigurator.doConfigure(GenericXMLConfigurator.java:170)
	at ch.qos.logback.core.joran.GenericXMLConfigurator.doConfigure(GenericXMLConfigurator.java:122)
	at ch.qos.logback.core.joran.GenericXMLConfigurator.doConfigure(GenericXMLConfigurator.java:65)
	at ch.qos.logback.classic.util.DefaultJoranConfigurator.configureByResource(DefaultJoranConfigurator.java:68)
	at ch.qos.logback.classic.util.DefaultJoranConfigurator.configure(DefaultJoranConfigurator.java:35)
	at ch.qos.logback.classic.util.ContextInitializer.invokeConfigure(ContextInitializer.java:128)
	at ch.qos.logback.classic.util.ContextInitializer.autoConfig(ContextInitializer.java:103)
	at ch.qos.logback.classic.util.ContextInitializer.autoConfig(ContextInitializer.java:66)
	at ch.qos.logback.classic.spi.LogbackServiceProvider.initializeLoggerContext(LogbackServiceProvider.java:52)
	at ch.qos.logback.classic.spi.LogbackServiceProvider.initialize(LogbackServiceProvider.java:41)
	at org.slf4j.LoggerFactory.bind(LoggerFactory.java:196)

**Comment by ceki** [comment]
@malikmuso Have you also upgraded logback-core?

**Comment by malikmuso** [comment]
Yes logback core and classic at version 1.5.6

[INFO] +- ch.qos.logback:logback-classic:jar:1.5.6:compile
[INFO] |  \- ch.qos.logback:logback-core:jar:1.5.6:compile

**Comment by ceki** [comment]
@malikmuso It looks like you have an older version of logback-core on your class path.

**Comment by dobbscr** [comment]
Upgraded logback-core to same version 1.5.6 and it now works ok.
Many thanks @ceki !
