### ISSUE TITLE
NoSuchMethodError when upgrading logback-core from 1.5.0 to 1.5.1

### ISSUE THREAD

**Issue by abendt** [qos-ch/logback#785]
When upgrading logback-core from 1.5.0 to 1.5.1 (or 1.5.2) in a SpringBoot application (Spring Boot 3.2.3) the app fails to start with this exception:

```
Logging system failed to initialize using configuration from 'null'
java.lang.NoSuchMethodError: 'void ch.qos.logback.core.model.ModelUtil.setProperty(ch.qos.logback.core.model.processor.ModelInterpretationContext, java.lang.String, java.lang.String, ch.qos.logback.core.joran.action.ActionUtil$Scope)'
	at org.springframework.boot.logging.logback.SpringPropertyModelHandler.handle(SpringPropertyModelHandler.java:60)
...
```

**Comment by ceki** [comment]
Hi @abendt  

Thank you for this report. The issue will be fixes in release 1.5.3
