### ISSUE TITLE
Logging System Fails to Initialize After Upgrading Logback to 1.5.16 (NoSuchMethodError in LogbackConfigurator)

### ISSUE THREAD

**Issue by kuanchengLiu** [qos-ch/logback#904]
Upgrading to logback  from 1.5.6 to 1.5.16 with tomcat resulting into
`Logging system failed to initialize using configuration from 'null'`

Spring Boot expects getConfigurationLock to return an Object and fails with NoSuchMethodError.

### Error Logs

```Java=
Logging system failed to initialize using configuration from 'null'
java.lang.NoSuchMethodError: 'java.lang.Object ch.qos.logback.classic.LoggerContext.getConfigurationLock()'
	at org.springframework.boot.logging.logback.LogbackConfigurator.getConfigurationLock(LogbackConfigurator.java:53)
	at org.springframework.boot.logging.logback.DefaultLogbackConfiguration.apply(DefaultLogbackConfiguration.java:57)
	... (stack trace continues)

```

### Environment

- Spring Boot Version: 3.2.9
- Logback Version: 1.5.16
- JDK Version: 21.0.1

**Comment by ceki** [comment]
@kuanchengLiu This issue is present in  Spring Boot version 3.2.x but has been fixed in Spring Boot version 3.3.3 and later. Please update to Spring Boot version 3.3.3 or later.

**Comment by nitinkumar-na** [comment]
For your information, upgrading to Spring Boot 3.3 is not that easy (at least for us). There are a lot of breaking changes that we need to adapt to.
You can't expect people to upgrade the framework version to fix a security vulnerability.

**Comment by wren0212** [comment]
Environment

- Spring Boot Version: 3.3.8
- Logback Version: 1.5.16
- JDK Version: 21.0.1
I meet the similar problem with message
java.lang.NoSuchFieldError: configurationLock
    at ch.qos.logback.classic.LoggerContext.stop(LoggerContext.java:364)
    at org.springframework.boot.logging.logback.LogbackLoggingSystem.stopAndReset (LogbackLoggingSystem.java:300)
     at org.springframework.boot.logging.logback.LogbackLoggingSystem.loadConfiguration (LogbackLoggingSystem.java:251)
     at org. springframework.boot.logging.AbstractLoggingSystem.initializeWithSpecificConfig(AbstractLoggingSystem.java:67)
